apps/cliente/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from . import views

app_name = "cliente"

urlpatterns = [
    # ---------------------- CLIENTE ---------------------- #
    url(r'^create-client/$', views.create_cliente, name="create_client"),
    url(r'^update-client/(?P<pk>\d+)$', views.update_cliente, name="update_client"),
    url(r'^set-password/(?P<pk>\d+)$', views.set_password, name="set_password"),
    url(r'^delete-client/(?P<pk>\d+)$', views.delete_cliente, name="delete_client"),

    # -------------------- COORDENADOR -------------------- #
    url(r'^create-coord/$', views.create_coord, name="create_coord"),
    url(r'^update-coord/(?P<pk>\d+)$', views.update_coord, name="update_coord"),
    url(r'^delete-coord/(?P<pk>\d+)$', views.delete_coord, name="delete_coord"),

    # ---------------------- MEMBRO ---------------------- #
    url(r'^member/$', views.list_membro, name="list_member"),
    url(r'^create-member/$', views.create_membro, name="create_member"),
    url(r'^update-member/(?P<pk>\d+)$', views.update_membro, name="update_member"),
    url(r'^update-member/(?P<pk>\d+)/(?P<comment_id>\d+)$', views.update_membro, name="update_member_comment"),
    url(r'^delete-member/(?P<pk>\d+)$', views.delete_membro, name="delete_member"),

    # ---------------------- GRUPO ---------------------- #
    url(r'^create-group/$', views.create_grupo, name="create_group"),
    url(r'^update-group/(?P<pk>\d+)$', views.update_grupo, name="update_group"),
    url(r'^delete-group/(?P<pk>\d+)$', views.delete_grupo, name="delete_group"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smart_event/urls.py
"""smart_event URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
# Django imports
from django.conf.urls import include, url, handler404, handler500
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_control
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
# from ..core.views import handler_404, handler_500

urlpatterns = [
    # Examples:
    # url(r'^blog/', include('blog.urls', namespace='blog')),

    # provide the most basic login/logout functionality
    # url(r'^login/$', auth_views.LoginView.as_view(template_name='core/login.html'),
    #     name='core_login'),
    # url(r'^logout/$', auth_views.LogoutView.as_view(), name='core_logout'),

    # enable the admin interface
    # url(r'^admin/', admin.site.urls),
    url(r'^acl/', include('apps.acl.urls', namespace="acl")),

    url(r'^', include('apps.dashboard.urls', namespace="dashboard")),

    url(r'^client/', include('apps.cliente.urls', namespace="client")),

    url(r'^coordinator/', include('apps.cliente.urls', namespace="coordinator")),

    url(r'^member/', include('apps.cliente.urls', namespace="member")),

    url(r'^group/', include('apps.cliente.urls', namespace="group")),

    url(r'^schedule/', include('apps.escala.urls', namespace="schedule")),

    url(r'^notification/', include('apps.notification.urls', namespace="notification")),

    url(r'^support/', include('apps.support.urls', namespace="support")),

    url(r'^location/', include('apps.location.urls', namespace="location")),

    url(r'^OneSignalSDKWorker.js', cache_control(max_age=2592000)(TemplateView.as_view(
      template_name="onesignal/OneSignalSDKWorker.js",
      content_type='application/javascript',
    )), name='OneSignalSDKWorker.js'),

    url(r'^OneSignalSDKUpdaterWorker.js', cache_control(max_age=2592000)(TemplateView.as_view(
      template_name="onesignal/OneSignalSDKUpdaterWorker.js",
      content_type='application/javascript',
    )), name='OneSignalSDKUpdaterWorker.js')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler404 = handler_404
# handler500 = handler_500

apps/cliente/models.py
from PIL import Image
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.utils.translation import gettext as _
from ..core.models import DefaultModel, UsuarioManager


# Create your models here.
class Client(DefaultModel, PermissionsMixin, AbstractBaseUser):

    login = models.CharField(_("Login"), max_length=50, unique=True)
    first_name = models.CharField(_("Primeiro Nome"), max_length=50)
    last_name = models.CharField(_("Último Nome"), max_length=50, null=True, blank=True)
    email = models.EmailField(_("Email"), max_length=254, null=True, blank=True)
    cpf_cnpj = models.CharField(_("CPF/CNPJ"), max_length=14, null=True, blank=False)
    telefone = models.CharField(_("Telefone"), max_length=13, null=True, blank=True)
    is_active = models.BooleanField(_("Ativo"), default=True, null=False, blank=True)
    logradouro = models.CharField(_("Endereço"), max_length=255, null=True, default=None, blank=True)
    numero = models.CharField(_("Número"), max_length=255, null=True, default=None, blank=True)
    complemento = models.CharField(_("Complemento"), max_length=255, null=True, default=None, blank=True)
    cep = models.CharField(_("CEP"), max_length=255, null=True, default=None, blank=True)
    bairro = models.CharField(_("Bairro"), max_length=255, null=True, default=None, blank=True)
    cidade = models.CharField(_("Cidade"), max_length=255, null=True, default=None, blank=True)
    uf = models.CharField(_("UF"), max_length=255, null=True, default=None, blank=True)
    data_nascimento = models.DateField(_("Data de Nascimento"), null=True, blank=True)
    foto = models.ImageField(_("Foto de Perfil"), null=True, blank=True, upload_to="profile/", default="profile/default-user.jpg")
    player_id = models.TextField(null=True, blank=True)
    checked = models.BooleanField(null=False, default=False)

    objects = UsuarioManager()

    USERNAME_FIELD = 'login'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

    class Meta:
        db_table = 'cliente'

    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    @property
    def full_address(self):
        return ", ".join([
            self.logradouro or '',
            self.numero or '',
            self.complemento or '',
            self.bairro or '',
            self.cidade or '',
            self.uf or ''
        ])

    @property
    def cidade_uf(self):
        return " - ".join([self.cidade, self.uf])

    @property
    def is_coordinator(self):
        return Coordinator.objects.filter(cliente=self).exists()

    @property
    def is_member(self):
        return Member.objects.filter(cliente=self).exists()


class Coordinator(DefaultModel):
    cliente = models.ForeignKey('cliente.Client', null=False, on_delete=models.CASCADE)
    grupo = models.ForeignKey('cliente.Group', null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        db_table = 'coordenador'

    def __str__(self):
        return self.cliente.full_name


class Member(DefaultModel):
    cliente = models.ForeignKey('cliente.Client', null=False, on_delete=models.CASCADE)
    grupo = models.ForeignKey('cliente.Group', null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        db_table = 'membro'

    def __str__(self):
        return self.cliente.full_name


class Group(DefaultModel):
    descricao = models.CharField(_("Descrição"), max_length=255, null=False, blank=False)

    class Meta:
        db_table = 'grupo'

    def __str__(self):
        return self.descricao

    def get_coordinators_name(self):
        return ", ".join(self.coordinator_set.all().values_list('cliente__first_name', flat=True))

apps/cliente/views.py
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.db.models import Q
from django.http import JsonResponse
from .forms import ClientForm, SetPasswordForm, GroupForm, CoordForm, MemberForm
from .models import Client, Coordinator, Member, Group
from ..core.utils import get_subdomain
from ..notification.models import Commentary
import re

@login_required
@user_passes_test(lambda u: u.is_superuser)
def create_cliente(request):
    form = ClientForm()
    password_form = SetPasswordForm()
    if request.method == 'POST':
        form = ClientForm(request.POST)
        password_form = SetPasswordForm(request.POST)
        if form.is_valid() and password_form.is_valid():
            cliente = form.save()
            cliente.set_password(password_form.cleaned_data.get('password1'))
            cliente.save()
            messages.success(request, "Cliente criado com sucesso!")
            return redirect('client:create_client')

    clientes = Client.objects.filter(is_active=True)
    context = {
        'form': form,
        'password_form': password_form,
        'clientes': clientes
    }
    return render(request, "cliente/create.html", context)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def update_cliente(request, pk):
    instance = get_object_or_404(Client, pk=pk)
    form = ClientForm(instance=instance)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            messages.success(request, "Cliente alterado com sucesso!")
            return redirect('client:create_client')

    context = {
        'form': form,
        'pk': pk
    }
    return render(request, "cliente/update.html", context)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def set_password(request, pk):
    cliente = get_object_or_404(Client, pk=pk)
    form = SetPasswordForm()

    if request.method == 'POST':
        form = SetPasswordForm(request.POST)
        if form.is_valid():
            cliente.set_password(form.cleaned_data.get('password1'))
            cliente.save()
            if request.user == cliente:
                update_session_auth_hash(request, cliente)

            messages.success(request, "Senha alterado com sucesso!")
        else:
            messages.error(request, form.errors.as_ul())
        return redirect('client:create_client')

    context = {
        'form': form,
        'pk': pk
    }
    return render(request, "cliente/set_password.html", context)


def delete_cliente(request, pk):
    try:
        cliente = get_object_or_404(Client, pk=pk)
        cliente.delete()
        messages.success(request, "Cliente removido com sucesso!")
    except Exception as exc:
        messages.error(request, "Erro ao remover cliente!")

    return JsonResponse({'result': 'success'})


# ---------------------- COORDENADOR ---------------------- #
@login_required
@user_passes_test(lambda u: u.is_superuser)
def create_coord(request):
    form = ClientForm()
    form_coord = CoordForm()
    password_form = SetPasswordForm()
    if request.method == 'POST':
        form = ClientForm(request.POST)
        form_coord = CoordForm(request.POST)
        password_form = SetPasswordForm(request.POST)
        if form.is_valid() and password_form.is_valid() and form_coord.is_valid():
            cliente = form.save()
            cliente.set_password(password_form.cleaned_data.get('password1'))
            cliente.save()
            Coordinator.objects.create(cliente=cliente, grupo=form_coord.cleaned_data.get('grupo'))
            messages.success(request, "Coordenador criado com sucesso!")
            return redirect('coordinator:create_coord')

    coords = Coordinator.objects.filter(cliente__is_active=True)
    context = {
        'form': form,
        'form_coord': form_coord,
        'password_form': password_form,
        'coords': coords
    }
    return render(request, 'coordenador/create.html', context)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def update_coord(request, pk):
    instance = get_object_or_404(Coordinator, pk=pk)
    form = ClientForm(instance=instance.cliente)
    form_coord = CoordForm(instance=instance)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=instance.cliente)
        form_coord = CoordForm(request.POST, instance=instance)
        if form.is_valid() and form_coord.is_valid():
            form.save()
            instance.grupo = form_coord.cleaned_data.get('grupo')
            instance.save()
            messages.success(request, "Coordenador alterado com sucesso!")
            return redirect('coordinator:create_coord')

    context = {
        'form': form,
        'form_coord': form_coord,
        'pk': pk
    }
    return render(request, "coordenador/update.html", context)


def delete_coord(request, pk):
    try:
        cliente = get_object_or_404(Client, pk=pk)
        cliente.delete()
        messages.success(request, "Coordenador removido com sucesso!")
    except Exception as exc:
        messages.error(request, "Erro ao remover coordenador!")

    return JsonResponse({'result': 'success'})


# ---------------------- MEMBRO ---------------------- #
@login_required
@user_passes_test(lambda u: u.is_superuser or u.is_coordinator)
def list_membro(request):
    form = ClientForm()
    form_member = MemberForm(user=request.user)
    members = Member.objects.filter(cliente__is_active=True)
    if request.user.is_coordinator:
        members = members.filter(Q(grupo__coordinator__cliente=request.user) | Q(grupo=None))

    context = {
        'form': form,
        'form_member': form_member,
        'members': members
    }
    return render(request, 'membro/create.html', context)


@login_required
@user_passes_test(lambda u: u.is_superuser or u.is_coordinator)
def create_membro(request):
    form = ClientForm()
    form_member = MemberForm(user=request.user)
    if request.method == 'POST':
        form = ClientForm(request.POST)
        form_member = MemberForm(request.POST)
        if form.is_valid() and form_member.is_valid():
            cliente = form.save(commit=False)
            cliente.telefone = re.sub(r'\D', '', cliente.telefone)
            cliente.cpf_cnpj = re.sub(r'\D', '', cliente.cpf_cnpj)
            cliente.save()
            member = Member.objects.create(cliente=cliente, grupo=form_member.cleaned_data.get('grupo'))
            # se usuario for coordenador, o grupo é selecionado automaticamente
            if request.user.is_coordinator:
                grupo = Coordinator.objects.get(cliente=request.user).grupo
                member.grupo = grupo
                member.save()
            messages.success(request, "Membro criado com sucesso!")
            return redirect('member:list_member')

    members = Member.objects.filter(cliente__is_active=True)
    if request.user.is_coordinator:
        members = members.filter(Q(grupo__coordinator__cliente=request.user) | Q(grupo=None))

    context = {
        'form': form,
        'form_member': form_member,
        'members': members
    }
    return render(request, 'membro/modals/create.html', context)


@login_required
@user_passes_test(lambda u: u.is_superuser or u.is_coordinator)
def update_membro(request, pk, comment_id=None):
    instance = get_object_or_404(Member, pk=pk)
    form_member = MemberForm(instance=instance, user=request.user)
    form = ClientForm(instance=instance.cliente)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=instance.cliente)
        form_member = MemberForm(request.POST, instance=instance)
        if form.is_valid() and form_member.is_valid():
            form.save()
            # se o usuario for admnistrador, pode alterar o grupo do membro
            if request.user.is_superuser:
                instance.grupo = form_member.cleaned_data.get('grupo')
                instance.save()
            messages.success(request, "Membro alterado com sucesso!")
            # tenta redirecionar para a pagina que chamou a requisicao.
            # se nao conseguir, por padrao redireciona para tela de membros
            try:
                with transaction.atomic(using=get_subdomain(request)):
                    if comment_id:
                        comment = Commentary.objects.get(id=comment_id)
                        comment.checked = True
                        comment.save()
                return redirect(request.META['HTTP_REFERER'])
            except:
                return redirect('member:create_member')

    context = {
        'form': form,
        'form_member': form_member,
        'pk': pk,
        'comment_id': comment_id
    }
    return render(request, 'membro/update.html', context)


def delete_membro(request, pk):
    try:
        cliente = get_object_or_404(Client, pk=pk)
        cliente.delete()
        messages.success(request, "Membro removido com sucesso!")
    except Exception as exc:
        messages.error(request, "Erro ao remover membro!")

    return JsonResponse({'result': 'success'})


# ---------------------- GRUPO ---------------------- #
@login_required
@user_passes_test(lambda u: u.is_superuser)
def create_grupo(request):
    form = GroupForm()
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Grupo criado com sucesso!")
            return redirect('group:create_group')

    groups = Group.objects.all()
    context = {
        'form': form,
        'groups': groups
    }
    return render(request, 'grupo/create.html', context)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def update_grupo(request, pk):

apps/cliente/templates/grupo/create.html
{% extends "index.html" %}
{% load static %}
{% load custom_filters %}

{% block title_page %}
  Grupos
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-6">
      {% include "grupo/includes/form.html" %}
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2 class="card-title">
            <i class="fas fa-list"></i>&nbsp;&nbsp;
            Grupos Ativos
          </h2>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand"></i></button>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
              <table id="example2" class="table dataTable table-bordered table-hover">
                <thead>
                <tr>
                  <th class="all">Descrição</th>
                  <th>Coordenador(es)</th>
                  <th class="all">Ações</th>
                </tr>
                </thead>
                <tbody>
                {% for group in groups %}
                  <tr>
                    <td>{{ group.descricao }}</td>
                    <td>{{ group.get_coordinators_name }}</td>
                    <td>
                      <div class="btn-group-sm btn-group">
                        <a title="Editar" class="btn btn-default" onclick="$('.modal-content').load('{% url "group:update_group" pk=group.id %}')" data-target="#ajax" data-toggle="modal"><i class="fas fa-pen"></i></a>
                        <button onclick="deletar_group({{ group.id }})" title="Remover" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                      </div>
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="ajax" role="basic" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-body">
          <i class="fas fa-sync fa-spin loading-img"></i>
          <span> &nbsp;&nbsp;Carregando…</span>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}" />
{% endblock %}
{% block js %}

  <script src="{% static "dist/js/ui-modals/ui-modals.min.js" %}"></script>
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
  <script src="{% static 'plugins/bootbox/bootbox.all.min.js' %}"></script>
  <script src="{% static 'plugins/bootbox/bootbox.locales.min.js' %}"></script>
  <script>
    $('#example2').DataTable({
      "autoWidth": false,
      "responsive": true,
    });

    $('#ajax').on('shown.bs.modal', function () {
      $('.date').datepicker({
        daysOfWeekHighlighted: '06',
        format: 'dd/mm/yyyy',
        todayHighlight: true,
        autoclose: true
      });
    })

    function deletar_group(id) {
      bootbox.confirm({
        title: "Ateção",
        message: "Deseja realmente remover este registro?",
        buttons: {
          cancel: {
            label: '<i class="fa fa-times"></i> Cancel'
          },
          confirm: {
            label: '<i class="fa fa-check"></i> Confirm',
            className: 'btn-danger'
          }
        },
        callback: function (result) {
          if (result == true) {
            $.ajax({
              url: `/group/delete-group/${id}`,
              complete: function (data) {
                window.location.reload();
              }
            })
          }
        }
      })
    }
  </script>
{% endblock %}

apps/cliente/templates/grupo/update.html
<div class="modal-header">
  <h4 class="modal-title">Editar Grupo</h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <form id="form_update" action="{% url 'group:update_group' pk=pk %}" method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label for="exampleInputEmail1">Descrição</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-sticky-note"></i></span>
            </div>
            {{ form.descricao }}
            {% if form.descricao.errors %}
              {% for error in form.descricao.errors %}
                <span class="error invalid-feedback">{{ error|escape }}</span>
              {% endfor %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
<div class="modal-footer justify-content-between">
  <button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
  <button type="submit" form="form_update" class="btn btn-primary" onclick="!this.form && document.getElementById('form_update').submit()"><i class="fas fa-check"></i> Salvar</button>
</div>