apps/escala/urls.py
from django.conf.urls import url
from . import views, api


app_name = 'escala'
urlpatterns = [
    url(r'^create/$', views.create, name="create"),
    url(r'^confirm-presence/$', views.confirmar_presenca, name="confirm_presence"),

    url(r'^api/create/$', api.create_schedule, name="api_create"),
    url(r'^api/update/(?P<pk>\d+)$', api.update_schedule, name="api_update"),
    url(r'^api/delete/(?P<pk>\d+)$', api.delete_schedule, name="api_delete"),
    url(r'^api/get-all-schedules/$', api.get_all_schedules, name="get_all_schedules"),
    url(r'^api/get-schedules-by-member/(?P<pk>\d+)$', api.get_schedules_by_member, name="get_schedules_by_member"),
    url(r'^api/get-member-by-schedule/$', api.get_member_by_schedule, name="get_member_by_schedule"),
    url(r'^api/get-member-by-schedule-html-form/$', api.get_member_by_schedule_html_form, name="get_member_by_schedule_html_form"),
    url(r'^api/set-presence/$', api.set_presence, name="set_presence"),
    url(r'^api/confirm-presence/$', api.confirm_presence_api, name="confirm_presence_api"),

    # criado especialmente para o dhxscheduler
    url(r'^create/api/get-member-by-schedule/$', api.get_member_by_schedule, name="get_member_by_schedule"),
]

smart_event/urls.py
"""smart_event URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
# Django imports
from django.conf.urls import include, url, handler404, handler500
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.decorators.cache import cache_control
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
# from ..core.views import handler_404, handler_500

urlpatterns = [
    # Examples:
    # url(r'^blog/', include('blog.urls', namespace='blog')),

    # provide the most basic login/logout functionality
    # url(r'^login/$', auth_views.LoginView.as_view(template_name='core/login.html'),
    #     name='core_login'),
    # url(r'^logout/$', auth_views.LogoutView.as_view(), name='core_logout'),

    # enable the admin interface
    # url(r'^admin/', admin.site.urls),
    url(r'^acl/', include('apps.acl.urls', namespace="acl")),

    url(r'^', include('apps.dashboard.urls', namespace="dashboard")),

    url(r'^client/', include('apps.cliente.urls', namespace="client")),

    url(r'^coordinator/', include('apps.cliente.urls', namespace="coordinator")),

    url(r'^member/', include('apps.cliente.urls', namespace="member")),

    url(r'^group/', include('apps.cliente.urls', namespace="group")),

    url(r'^schedule/', include('apps.escala.urls', namespace="schedule")),

    url(r'^notification/', include('apps.notification.urls', namespace="notification")),

    url(r'^support/', include('apps.support.urls', namespace="support")),

    url(r'^location/', include('apps.location.urls', namespace="location")),

    url(r'^OneSignalSDKWorker.js', cache_control(max_age=2592000)(TemplateView.as_view(
      template_name="onesignal/OneSignalSDKWorker.js",
      content_type='application/javascript',
    )), name='OneSignalSDKWorker.js'),

    url(r'^OneSignalSDKUpdaterWorker.js', cache_control(max_age=2592000)(TemplateView.as_view(
      template_name="onesignal/OneSignalSDKUpdaterWorker.js",
      content_type='application/javascript',
    )), name='OneSignalSDKUpdaterWorker.js')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler404 = handler_404
# handler500 = handler_500

apps/escala/models.py
from django.db import models
from django.utils import timezone

from ..cliente.models import Group
from ..core.models import DefaultModel
from django.utils.translation import gettext as _


class Schedule(DefaultModel):
    descricao = models.TextField(_("Descrição"), null=True, blank=True)
    inicio = models.DateTimeField(_("Início"), null=False, blank=False, default=timezone.now)
    fim = models.DateTimeField(_("Fim"), null=False, blank=False, default=timezone.now)
    obs = models.TextField(_("OBS"), null=True, blank=True)
    # grupo = models.ForeignKey('cliente.Group', null=True)

    class Meta:
        db_table = 'escala'

    def __str__(self):
        return self.descricao

    def get_group(self):
        try:
            return Group.objects.get(member__schedulemember__escala=self)
        except Group.DoesNotExist:
            return None


class ScheduleMember(DefaultModel):
    escala = models.ForeignKey('escala.Schedule', null=False, blank=False, on_delete=models.CASCADE)
    membro = models.ForeignKey('cliente.Member', null=False, blank=False, on_delete=models.CASCADE)
    presenca = models.BooleanField(default=False, null=False, blank=True)

    class Meta:
        db_table = 'escala_membro'

    def __str__(self):
        return self.membro.cliente.first_name + ' - ' + self.escala.descricao

apps/escala/forms.py
from django import forms

from apps.cliente.models import Member


class CreateScheduleForm(forms.Form):
    nome = forms.CharField(required=True, localize=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nome'
    }))
    data = forms.DateField(required=True, localize=True, widget=forms.DateInput(attrs={
        'class': 'form-control',
        'placeholder': 'Data',
        'type': 'date'
    }))
    hora = forms.TimeField(required=True, localize=True, widget=forms.TimeInput(attrs={
        'class': 'form-control',
        'placeholder': 'Hora',
        'type': 'time'
    }))
    membro = forms.ModelMultipleChoiceField(required=True, queryset=Member.objects.all(), widget=forms.SelectMultiple(attrs={
        'class': "form-control select2",
        'multiple': "multiple",
        'data-placeholder': "Selecione os membros",
        'data-dropdown-css-class': "select2-primary"
    }))

    def __init__(self, *args, **kwargs):
        grupo = kwargs.pop('grupo', None)
        super(CreateScheduleForm, self).__init__(*args, **kwargs)
        if grupo:
            self.fields['membro'].queryset = Member.objects.filter(grupo=grupo)

apps/escala/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import ScheduleMember
from ..cliente.models import Coordinator, Member
from ..escala.forms import CreateScheduleForm


@login_required
def create(request):
    if request.user.is_coordinator:
        grupo = Coordinator.objects.get(cliente=request.user).grupo
    else:
        grupo = None
    form = CreateScheduleForm(grupo=grupo)
    context = {
        'form': form
    }
    return render(request, 'escala/create.html', context)


def confirmar_presenca(request):
    player_id = request.GET.get('player_id', '')
    schedule_id = request.GET.get('schedule_id', '')
    context = {
        'player_id': player_id,
        'schedule_id': schedule_id
    }

    try:
        member = Member.objects.get(cliente__player_id=player_id)
        schedule_member = ScheduleMember.objects.get(escala=schedule_id, membro=member)
        context.update({
            'schedulemember_id': schedule_member.id,
            'message': 'Utilizamos sua localização para verificar que você realmente está em <strong>{}</strong> 📍.'.format('Paróquia Imaculada Conceição'),
            'title': 'Presença Confirmada 😉',
            'status': 'success'
        })
    except (Member.DoesNotExist, Member.MultipleObjectsReturned) as exc:
        context.update({
            'schedulemember_id': None,
            'message': 'Não conseguimos identificar seu cadastro no sistema.',
            'title': 'Sentimos Muito 😔',
            'status': 'error'
        })
    except (ScheduleMember.DoesNotExist, ScheduleMember.MultipleObjectsReturned) as exc:
        context.update({
            'schedulemember_id': None,
            'message': 'Não conseguimos identificar esta Escala.',
            'title': 'Sentimos Muito 😔',
            'status': 'error'
        })

    return render(request, 'confirmar_presenca/confirmar_presenca.html', context)

apps/escala/templates/confirmar_presenca/confirmar_presenca.html
{% load custom_filters %}
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Smart Schedule | Confirmar Presença</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static "plugins/icheck-bootstrap/icheck-bootstrap.min.css"%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
  <link rel="stylesheet" href="{% static "plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css" %}">
  <link rel="stylesheet" href="{% static "plugins/sweetalert2/sweetalert2.min.css" %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <link rel="shortcut icon" href="{% static 'dist/img/logotipo/favicon.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'dist/img/logotipo/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'dist/css/global/styles.css' %}" />
  <link rel="stylesheet/less" href="{% static 'dist/css/global/svg_check.less' %}" />
</head>

<body class="hold-transition login-page">
<div class="container login login-box">
  <div class="login-logo">
    <a href="#">
      <img alt="logotipo" src="{% static "dist/img/logotipo/275x100.png" %}" />
    </a>
  </div>
  <!-- /.login-logo -->
  <div class="card bg-light elevation-3">
    {#    <div class="card-header text-muted border-bottom-0"></div>#}
    <div class="card-body pt-0" style="text-align: center">
      <!--[if lte IE 9]>
      <style>
        .path {stroke-dasharray: 0 !important;}
      </style>
      <![endif]-->
      <div id="svg_content">
        <svg version="1.1" id="L3" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 0 0" xml:space="preserve">
          <circle fill="none" stroke="#ccc" stroke-width="4" cx="50" cy="50" r="44" style="opacity:0.5;"/>
            <circle fill="#fff" stroke="#28a745" stroke-width="3" cx="8" cy="54" r="6" >
              <animateTransform attributeName="transform" dur="2s" type="rotate" from="0 50 48" to="360 50 52" repeatCount="indefinite" />
            </circle>
          </svg>
          <span>Aguarde...</span>
      </div>
    </div>
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.min.js" %}"></script>
<script src="{% static "plugins/bootbox/bootbox.all.min.js" %}"></script>
<script src="{% static "plugins/sweetalert2/sweetalert2.all.min.js" %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.3/less.min.js"></script>
<script>
  $(document).ready(function () {
    // Try HTML5 geolocation.
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
              function (position) {
                var lat = position.coords.latitude;
                var lng = position.coords.longitude;
                $.ajax({
                  'url': '{% url 'schedule:confirm_presence_api' %}',
                  'method': 'post',
                  'data': {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    lat: lat,
                    lng: lng,
                    player_id: '{{ player_id }}',
                    schedule_id: '{{ schedule_id }}',
                    schedulermember_id: '{{ schedulemember_id }}'
                  },
                  success: function (data) {
                    $('#svg_content').fadeOut(500, function () {
                      $(this).html(`
                    ${ data.status == 'success' ?
                              `
                      <svg height="100" width="100" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130.2 130.2">
                        <circle class="path circle" fill="none" stroke="#73AF55" stroke-width="6" stroke-miterlimit="10" cx="65.1" cy="65.1" r="62.1"/>
                        <polyline class="path check" fill="none" stroke="#73AF55" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" points="100.2,40.2 51.5,88.8 29.8,67.5 "/>
                      </svg>
                      <br>
                      <h3 class="text-center text-success">${data.title}</h3>
                      <span>${data.message}</span>
                      ` :
                              `
                      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130.2 130.2">
                        <circle class="path circle" fill="none" stroke="#D06079" stroke-width="6" stroke-miterlimit="10" cx="65.1" cy="65.1" r="62.1"/>
                        <line class="path line" fill="none" stroke="#D06079" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" x1="34.4" y1="37.9" x2="95.8" y2="92.3"/>
                        <line class="path line" fill="none" stroke="#D06079" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" x1="95.8" y1="38" x2="34.4" y2="92.2"/>
                      </svg>
                      <br>
                      <h3 class="text-center text-danger">${data.title}</h3>
                      <span>${data.message}</span>
                      `}
                    `)
                    }).fadeIn(500)
                  },
                  error: function () {
                    alert('Ocorreu um erro ao verificar sua localização. 😪');
                  }
                })
              },
              function () {
                alert('Por favor, habilite a localização no seu dispositivo e atualize a página! 😊');
                $('#svg_content').fadeOut(500, function () {
                  $(this).html(`
                      <img alt height="50%" width="50%" src="{% static 'dist/img/logotipo/location_marker.svg' %}" />
                      <br>
                      <h3 class="text-center text-danger">Habilite a localização!</h3>
                    `)
                }).fadeIn(500)
              }
      );
    } else {
      // Browser doesn't support Geolocation
      handleLocationError(false, infoWindow, map.getCenter());
    }
  })
</script>
</body>
</html>